name: streamlit-r-env
channels:
  - conda-forge
dependencies:
  # --- PHẦN 1: HỆ THỐNG & R (Cài bằng Conda) ---
  - python=3.10
  - pip  # Bắt buộc phải cài pip để chạy phần dưới
  
  # R Core
  - r-base=4.3.3
  
  # R Packages (Binary siêu tốc)
  - r-ggplot2
  - r-dplyr
  - r-gtsummary
  - r-survival
  - r-survminer
  - r-flextable
  - r-remotes
  - r-systemfonts
  - r-textshaping
  - r-broom
  - r-broom.helpers
  - r-gt  
  
  # --- PHẦN 2: THƯ VIỆN PYTHON (Cài bằng PIP) ---
  # Cài bằng pip sẽ đảm bảo không bao giờ bị lỗi ModuleNotfound
  - pip:
    - streamlit
    - pandas
    - openai
