name: streamlit-r-env
channels:
  - conda-forge # Chỉ dùng duy nhất nguồn này để tránh xung đột tính toán
dependencies:
  # Python dependencies
  - python=3.9
  - streamlit
  - pandas
  - openai
  
  # R Core
  - r-base=4.3.1
  
  # R Packages (Cài từ conda-forge binary rất nhanh)
  - r-ggplot2
  - r-dplyr
  - r-gtsummary
  - r-survival
  - r-survminer
  - r-flextable
  - r-remotes
  # Các thư viện phụ trợ hệ thống (để tránh lỗi hiển thị font)
  - r-systemfonts
  - r-textshaping
