name: streamlit-r-env
channels:
  - conda-forge
dependencies:
  # Cài Python nền và Pip (bắt buộc để chạy requirements.txt sau này)
  - python=3.10
  - pip
  
  # R Core
  - r-base=4.3.1
  
  # Các thư viện R (Binary từ conda-forge)
  - r-ggplot2
  - r-dplyr
  - r-gtsummary
  - r-survival
  - r-survminer
  - r-flextable
  - r-remotes
  - r-systemfonts
  - r-textshaping
